name: ppg_workshop_showcase
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.11
- pip
- git
- pip:
  - ppg-experiment-framework[workshop] @ git+https://github.com/PPG-BP-Framework/ppg-workshop.git@v0.1.4
